apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aewehr-api-autoscaler 
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aewehr-api-deployment
  targetCPUUtilizationPercentage: 50
