apiVersion: v1
kind: ServiceAccount
metadata:
  name: poduser
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: poduserrole
   namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list", "create", "update", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: poduserrolebinding
   namespace: default
subjects:
- kind: ServiceAccount
  name: poduser
  namespace: default
roleRef:
  kind: Role
  name: poduserrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: poduser-secret
  annotations:
    kubernetes.io/service-account.name: poduser
type: kubernetes.io/service-account-token

