apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlstorage
  labels:
    app: mysql
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.1.240
    path: "/mydbdata"
